name: vetconnectapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.14
  url_launcher_windows: ^3.0.0
  http: ^1.3.0
  font_awesome_flutter: ^10.0.0
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.10.0 
  shared_preferences: ^2.2.4
  geolocator: ^13.0.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  get: ^4.6.6
  permission_handler: ^11.4.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.0
  flutter_local_notifications: ^18.0.1
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets: 
    - assets/vetconnectlogo.png
    - assets/fondovetconnectconhuellitas.png  
    - assets/huellita_inicio_de_sesion.png  
    - assets/usuario.png
    - assets/veterinario.png
    - assets/vetconnecticonfondo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/vetconnecticonfondo.png" 
