name: vetconnectapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  font_awesome_flutter: ^10.0.0
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.10.0  # Esta línea ahora está correctamente indentada bajo 'dependencies'
  shared_preferences: ^2.2.4
  geolocator: ^10.0.0
  maplibre_gl: ^0.20.0
  latlong2: ^0.9.1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/vetconnectlogo.png
    - assets/fondovetconnectconhuellitas.png  
    - assets/huellita_inicio_de_sesion.png  
